services:
  coordinator:
    build:
      context: .
      dockerfile: gpu_coordinator/Dockerfile
    container_name: coordinator
    ports:
      - "8082:8082"
    command: ["./gpu_coordinator_server", "--config_file=/app/config.json", "--port=8082"]
    # ^ override CMD from the Dockerfile
    depends_on:
      - etcd
    environment:
      - ETCD_ENDPOINTS=http://etcd:2379 # etcd endpoint for the coordinator

  gpu_device_0:
    build:
      context: .
      dockerfile: gpu_device/Dockerfile
    container_name: device0
    ports:
      - "9001:9001"
    command: ["./gpu_device_server", "--device_id=0", "--config_file=/app/config.json"]
    # ^ override CMD: device1 listens on port=9001, referencing deviceId=1

  gpu_device_1:
    build:
      context: .
      dockerfile: gpu_device/Dockerfile
    container_name: device1
    ports:
      - "9002:9002"
    command: ["./gpu_device_server", "--device_id=1", "--config_file=/app/config.json"]

  gpu_device_2:
    build:
      context: .
      dockerfile: gpu_device/Dockerfile
    container_name: device2
    ports:
      - "9003:9003"
    command: ["./gpu_device_server", "--device_id=2", "--config_file=/app/config.json"]

  gpu_device_3:
    build:
      context: .
      dockerfile: gpu_device/Dockerfile
    container_name: device3
    ports:
      - "9004:9004"
    command: ["./gpu_device_server", "--device_id=3", "--config_file=/app/config.json"]

  gpu_device_4:
    build:
      context: .
      dockerfile: gpu_device/Dockerfile
    container_name: device4
    ports:
      - "9005:9005"
    command: ["./gpu_device_server", "--device_id=4", "--config_file=/app/config.json"]
  
  gpu_device_5:
    build:
      context: .
      dockerfile: gpu_device/Dockerfile
    container_name: device5
    ports:
      - "9006:9006"
    command: ["./gpu_device_server", "--device_id=5", "--config_file=/app/config.json"]
  
  gpu_device_6:
    build:
      context: .
      dockerfile: gpu_device/Dockerfile
    container_name: device6
    ports:
      - "9007:9007"
    command: ["./gpu_device_server", "--device_id=6", "--config_file=/app/config.json"]
  
  gpu_device_7:
    build:
      context: .
      dockerfile: gpu_device/Dockerfile
    container_name: device7
    ports:
      - "9008:9008"
    command: ["./gpu_device_server", "--device_id=7", "--config_file=/app/config.json"]
  
  gpu_device_8:
    build:
      context: .
      dockerfile: gpu_device/Dockerfile
    container_name: device8
    ports:
      - "9009:9009"
    command: ["./gpu_device_server", "--device_id=8", "--config_file=/app/config.json"]
  
  gpu_device_9:
    build:
      context: .
      dockerfile: gpu_device/Dockerfile
    container_name: device9
    ports:
      - "9010:9010"
    command: ["./gpu_device_server", "--device_id=9", "--config_file=/app/config.json"]
  
  gpu_device_10:
    build:
      context: .
      dockerfile: gpu_device/Dockerfile
    container_name: device10
    ports:
      - "9011:9011"
    command: ["./gpu_device_server", "--device_id=10", "--config_file=/app/config.json"]

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: client
    environment:
      - TEST=${TEST}
      - ALGO=${ALGO}
      - FAIL=${FAIL}
    depends_on:
      - coordinator
      - gpu_device_0
      - gpu_device_1
      - gpu_device_2
      - gpu_device_3
    command: ["--config_file=/app/config.json"]

  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    ports:
      - "2379:2379" # Client communication port
      - "2380:2380" # Peer communication port
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes # Disable authentication for simplicity
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
